<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * 
 * Contao extension: zExtendedRegistration
 * English translation file 
 * 
 * Copyright : Tim Gatzky 2012 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), www.tim-gatzky.de 
 * Translator: Tim Gatzky
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['recommended_error'] = "Recommendation (%s), not found. Please verify your entries, or leave the field empty.";
$GLOBALS['TL_LANG']['MSC']['field_description'] = "Field description %s";

?>
