<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * 
 * Contao extension: zExtendedRegistration
 * English translation file 
 * 
 * Copyright : Tim Gatzky 2012 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), www.tim-gatzky.de 
 * Translator: Tim Gatzky
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['extReg_recommendation'] = array('Verify recommendation', 'Check before activation if the new member was recommended by an existing user. If true, the activation mail will be send directely. If not the admin must activate the new account. Please select the recommendation fields from above.');
$GLOBALS['TL_LANG']['tl_module']['extReg_cron'] = array('Delayed activation', 'Send the activation mail later.');
$GLOBALS['TL_LANG']['tl_module']['extReg_cron_delay'] = array('Delay in minutes', 'Enter the delay in minutes before sending (min. 5 min.)');
$GLOBALS['TL_LANG']['tl_module']['extReg_addformfields'] = array('Additional fields', 'Exend the registration form with additional fields taken from the formgenerator');
$GLOBALS['TL_LANG']['tl_module']['extReg_form'] = array('Forms', 'Please choose the form that holds the form fields.');
$GLOBALS['TL_LANG']['tl_module']['extReg_formfields'] = array('Formfields', 'Please choose the fields.');
$GLOBALS['TL_LANG']['tl_module']['extReg_adminOnly'] = array('Admin activation only', 'The admin has to active the new member no matter what.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['extReg_legend'] = 'More Settings';


?>