<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');

/**
 * 
 * Contao extension: zExtendedRegistration
 * English translation file 
 * 
 * Copyright : Tim Gatzky 2012 
 * License   : LGPL 
 * Author    : Tim Gatzky (Timmm), www.tim-gatzky.de 
 * Translator: Tim Gatzky
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_member']['recommended_from_email'] = array('Recommendation from (Email-address)', 'The Email-address that has to verified before register the new member.');
$GLOBALS['TL_LANG']['tl_member']['recommended_from_username'] = array('Recommendation from (Username)', 'The username that has to verified before register the new member.');
$GLOBALS['TL_LANG']['tl_member']['email_confirmation'] = array('Email confirmation', 'Please reenter your Email-address');


/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_member']['recommendation_legend'] = 'Recommendation from';
$GLOBALS['TL_LANG']['tl_member']['z_extended_registration_fields_legend'] = 'Fields taken from fieldgenerator';


?>